const baseUrl =
  'https://raw.githubusercontent.com/primavera133/dragonsGraphQLAPI/master/api/data/'

const dataTree = {
  aeshnidae: [
    'aeshna-affinis',
    'aeshna-caerulea',
    'aeshna-crenata',
    'aeshna-cyanea',
    'aeshna-grandis',
    'aeshna-isoceles',
    'aeshna-juncea',
    'aeshna-mixta',
    'aeshna-serrata',
    'aeshna-subarctica',
    'aeshna-viridis',
    'anax-ephippiger',
    'anax-imaculifrons',
    'anax-imperator',
    'anax-junius',
    'anax-parthenope',
    'boyeria-cretensis',
    'boyeria-irene',
    'brachytron-pratense',
    'caliaeschna-microstigma'
  ],
  calopterygidae: [
    'calopteryx-haemorrhoidalis',
    'calopteryx-splendens',
    'calopteryx-virgo',
    'calopteryx-xanthostoma'
  ],
  coenagrionidae: [
    'ceriagrion-georgifreyi',
    'ceriagrion-tenellum',
    'coenagrion-armatum',
    'coenagrion-caerulescens',
    'coenagrion-ecornutum',
    'coenagrion-glaciale',
    'coenagrion-hastulatum',
    'coenagrion-hylas',
    'coenagrion-intermedium',
    'coenagrion-johanssonii',
    'coenagrion-lunulatum',
    'coenagrion-mercuriale',
    'coenagrion-ornatum',
    'coenagrion-puella',
    'coenagrion-pulchellum',
    'coenagrion-scitulum',
    'enallagma-cyathigerum',
    'erythromma-lindenii',
    'erythromma-najas',
    'erythromma-viridulum'
  ],
  cordulegastridae: [
    'cordulegaster-bidentata',
    'cordulegaster-boltonii',
    'cordulegaster-helladica',
    'cordulegaster-heros',
    'cordulegaster-insignis',
    'cordulegaster-picta',
    'cordulegaster-trinacriae'
  ],
  corduliidae: [
    'macromia-splendens',
    'cordulia-aenea',
    'epitheca-bimaculata',
    'oxygastra-curtisii',
    'somatochlora-alpestris',
    'somatochlora-arctica',
    'somatochlora-borisi',
    'somatochlora-flavomaculata',
    'somatochlora-meridionalis',
    'somatochlora-metallica',
    'somatochlora-sahlbergi'
  ],
  euphaeidae: ['epallage-fatime'],
  gomphidae: [
    'lindenia-tetraphylla',
    'gomphus-flavipes',
    'gomphus-graslinii',
    'gomphus-pulchellus',
    'gomphus-schneiderii',
    'gomphus-simillimus',
    'gomphus-vulgatissimus',
    'onychogomphus-costae',
    'onychogomphus-forcipatus',
    'onychogomphus-uncatus',
    'ophiogomphus-cecilia',
    'paragomphus-genei'
  ],
  lestidae: [
    'chalcolestes-parvidens',
    'chalcolestes-viridis',
    'lestes-barbarus',
    'lestes-dryas',
    'lestes-macrostigma',
    'lestes-sponsa',
    'lestes-virens',
    'sympecma-fusca',
    'sympecma-paedisca'
  ],
  libellulidae: [
    'brachythemis-impartita',
    'crocothemis-erythraea',
    'leucorrhinia-albifrons',
    'brachythemis-impartita',
    'crocothemis-erythraea',
    'leucorrhinia-albifrons',
    'leucorrhinia-caudalis',
    'leucorrhinia-dubia',
    'leucorrhinia-pectoralis',
    'leucorrhinia-rubicunda',
    'libellula-depressa',
    'libellula-fulva',
    'libellula-quadrimaculata',
    'orthetrum-albistylum',
    'orthetrum-brunneum',
    'orthetrum-cancellatum',
    'orthetrum-chrysostigma',
    'orthetrum-coerulescens',
    'orthetrum-nitidinerve',
    'orthetrum-sabina',
    'orthetrum-taeniolatum',
    'orthetrum-trinacria',
    'pantala-flaviscens',
    'selysiothemis-nigra',
    'sympetrum-danae',
    'sympetrum-depressiculum',
    'sympetrum-flaveolum',
    'sympetrum-fonscolombii',
    'sympetrum-lefebvrii',
    'sympetrum-meridionale',
    'sympetrum-nigrifemur',
    'sympetrum-pedemontanum',
    'sympetrum-sanguineum',
    'sympetrum-sinaiticum',
    'sympetrum-striolatum',
    'sympetrum-vulgatum',
    'thrithemis-annulata',
    'thrithemis-arteriosa',
    'thrithemis-festiva',
    'thrithemis-kirbyi',
    'zygonyx-torridus'
  ],
  platychnemididae: [
    'platychnemis-acutipennis',
    'platychnemis-latipes',
    'platychnemis-pennipes'
  ]
}

export default {
  baseUrl,
  dataTree
}
